name: 'CI Privacy Alert'
description: 'Detect changes in OpenAPI Spec and write them to DB'

inputs:
  source-specification:  
    description: 'Source spec'
    required: true
  changed-specification:  
    description: 'Changed spec'
    required: true
  db-connection:
    description: 'DB Connection string'
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-specification }}
    - ${{ inputs.changed-specification }}
    - ${{ inputs.db-connection }}